
Harness Error (TIMEOUT), message = null

FAIL callback's result is promisified if not async promise_test: Unhandled rejection with value: object "NotSupportedError: The operation is not supported."
TIMEOUT lock is held until callback's returned promise resolves Test timed out
NOTRUN lock is held until callback's returned promise rejects
NOTRUN held lock prevents the same client from acquiring it

